### ISSUE TITLE
Update sites using localist_pane

### ISSUE THREAD

**Issue by richardbporter** [ITS-UofIowa/localist_pane#13]
To use the new event calendar system.

# 701
## Custom sites

- [x] hawktools.uiowa.edu

## Standard sites

- [x] mssui.org.uiowa.edu
- [x] ieee.org.uiowa.edu
- [x] uiowa.edu/jmpec
- [x] uiowa.edu/csw
- [x] uiowa.edu/uilatinocouncil
- [x] uiowa.edu/stem
- [x] uiowa.edu/staff

# 702

- [x] iowateacherintern.org
- [x] hawkit.sports.uiowa.edu

# 703

- [x] grantwood.uiowa.edu
- [x] researchpark.uiowa.edu -- will need to be swapped out manually after events.uiowa.edu change-over. See comment below.
- [x] discover.research.uiowa.edu -- will need to deploy [PR1](https://github.com/ITS-UofIowa/discover.research.uiowa.edu/pull/1)           
- [x] outreach.uiowa.edu                   
- [x] iisc.uiowa.edu
- [x] uc.uiowa.edu -- will need to deploy [PR4](https://github.com/ITS-UofIowa/uc.uiowa.edu/pull/4)
- [x] oldcap.uiowa.edu
- [x] desmoines.uiowa.edu
- [x] cbb.research.uiowa.edu -- will need to deploy [PR2](https://github.com/ITS-UofIowa/cbb.research.uiowa.edu/pull/2)
- [x] research.uiowa.edu -- will need to deploy [PR2](https://github.com/ITS-UofIowa/research.uiowa.edu/pull/2). see comment below.                 
- [x] artshare.uiowa.edu
- [x] now.uiowa.edu                      
- [x] teach.its.uiowa.edu               
- [x] law.uiowa.edu                 
- [x] its.uiowa.edu

**Comment by genjohnson** [comment]
For the standard service, this will involve:

- Checking if documentation needs to be updated and making any necessary changes
- Adding uiowa_events to the uiowa_standard_profile make file
- Allow uiowa_events pane to be placed on panelized content
- Providing CSS in each theme for the uiowa_events pane
- In hook_install() of the profile, enabling uiowa_events (we only need the pane for now)
- Writing an update hook to enable uiowa_events (we only need the pane for now)
- Manually replace Localist panes with uiowa_events pane

then after all of the tasks above are done...
- Removing Localist pane as an allowed pane to placed on panelized content
- Removing CSS in each theme for localist_pane
- Disabling & uninstalling localist_pane 
- Removing localist_pane from the uiowa_standard_profile make file

The switch to uiowa_events can be done at any time since we will be providing update hooks in uiowa_events to update/migrate config to work with the new system.

**Comment by genjohnson** [comment]
The branch `uiowa_events` for research.uiowa.edu is ready to be released, but must be released at the same time as https://github.com/ITS-UofIowa/sitenow_custom_profile/pull/226

**Comment by genjohnson** [comment]
## researchpark.uiowa.edu
1. Enable uiowa_events_pane
2. Add uiowa_events_pane on homepage
    - CSS class: `pane-uiowa-events-pane-list`
    - Display events tagged with Department `UI Research Park` & Event General Interest `Economic and Community Development`
3. Remove Localist pane from homepage
4. Disable & uninstall localist_pane

**Comment by richardbporter** [comment]
Neither of iowateacherintern.org or hawkit.sports.uiowa.edu have a pane of type localist_pane in the database.

**Comment by richardbporter** [comment]
- [ ] Update hook to disable and uninstall localist_pane
- [ ] Remove localist_pane from make file

**Comment by richardbporter** [comment]
I think this task is done. See https://github.com/ITS-UofIowa/sitenow_standard_profile/issues/171 for a follow-up.
